### ISSUE TITLE
Webseite: Fahrplan direkt nach Kursformat?

### ISSUE THREAD

**Issue by cyildiz** [Artificial-Intelligence-HSBI-TDU/KI-Vorlesung#373]
Fahrplan direkt nach Kursformat?
  - Der Fahrplan ist voraussichtlich der am meisten benutzte Teil der Webseite.
  - In den Shortcut-Links kommt es vor Note/Credits.
  - Vorgeschlagene Reihenfolge: Team - Kursformat - Fahrplan - Prüfungsform - Materialien  
  - Bei der Vorstellung in der ersten Sprechstunde passt es auch gut in obiger Reihenfolge.

Die "Keywords" im graphischen Fahrplan auch in die Fahrplan-Tabelle übertragen?
 - Zusammenhang zwischen graphischem Fahrplan und Menü-Items ist mehr oder weniger klar. Vorschlag:
   - Statt "Games" -> "Spiele" schreiben?
   - Statt "EA/GA"  -> "Genetische Alg." schreiben?
 - Zusammenhang zwischen Einträgen in der Fahrplan-Tabelle und den Menü-Items nicht immer ganz klar. Vorschlag:
   - Zu den NN-Themen im Fahrplan NN01, NN02 hinzufügen?
   - In KW01 das Keyword "DTL" einbauen?

**Comment by cagix** [comment]
> * Der Fahrplan ist voraussichtlich der am meisten benutzte Teil der Webseite.
> * In den Shortcut-Links kommt es vor Note/Credits.
> * Vorgeschlagene Reihenfolge: Team - Kursformat - Fahrplan - Prüfungsform - Materialien
> * Bei der Vorstellung in der ersten Sprechstunde passt es auch gut in obiger Reihenfolge.

@cyildiz Merkwürdig, ich hatte dieser Tage auch darüber nachgedacht... 

Ich würde sogar noch einen Schritt weiter gehen: An sich sind alle Informationen bis auf den Fahrplan nur für den ersten Termin wichtig und im laufenden Semester nicht mehr relevant. Oft hat man dafür dann eine extra Unterseite "Syllabus". Das hatten wir schon mal, aber ich finde es eigentlich schöner, wenn alle relevanten Dinge zur Orga auf einer Seite zu finden sind. 

Die Materialien hatte ich extra nach vorne gezogen, damit es nicht so wirkt, als ob sie nicht wirklich relevant sind. 

Ich hatte auch überlegt, ob man die Abschnitte ausklappbar macht. Aber das verbessert die Lesbarkeit nicht wirklich aus meiner Sicht.

Wenn ich Studi wäre, würde ich mir einfach einmal einen Bookmark auf den Fahrplan anlegen und in Zukunft immer direkt dorthin springen.

---

Wenn es Dir besser zum Erzählfluss passt, kann ich die Reihenfolge aber gern umstellen.

**Comment by cagix** [comment]
> Die "Keywords" im graphischen Fahrplan auch in die Fahrplan-Tabelle übertragen?
> 
> * Zusammenhang zwischen graphischem Fahrplan und Menü-Items ist mehr oder weniger klar. Vorschlag:
>   
>   * Statt "Games" -> "Spiele" schreiben?
>   * Statt "EA/GA"  -> "Genetische Alg." schreiben?
> * Zusammenhang zwischen Einträgen in der Fahrplan-Tabelle und den Menü-Items nicht immer ganz klar. Vorschlag:
>   
>   * Zu den NN-Themen im Fahrplan NN01, NN02 hinzufügen?
>   * In KW01 das Keyword "DTL" einbauen?

Gute Punkte! 

Ich glaube, dass die Studis die "Übersetzung" hinbekommen, so dass kein Bedarf für eine ad hoc Lösung besteht. Aber mittelfristig sollte man das mal angehen.

An sich sehe ich drei Stellen, die adressiert werden sollten:

1. Prinzipiell bin ich mit den Begriffen/Abkürzungen im Überblicksbild ganz zufrieden. Das "Games" sticht insofern dort heraus, als dass es der einzige englische Begriff ist. D.h. hier könnte man im Bild statt "Games" besser "Spiele" schreiben.
2. Im Fahrplan könnte in jeder Zeile am Anfang das Themen-Kürzel auftauchen. Also beispielsweise für KW41: "NN: Machine Learning 101, Perzeptron". Da könnten wir die Kürzel aus der Überblicksgrafik nehmen.
3. Im Menü könnte man das entsprechend übertragen. Also statt dem Top-Level-Eintrag "Neuronale Netze" könnte das heissen "NN: Neuronale Netze".

Aber dann passt das Überblicksbild irgendwie nicht mehr - dort verwenden wir bei mehrwöchigen Themen wie "NN" kein Kürzel. Ich würde in der Grafik auch ungern noch ein Kürzel mit einbauen, dann leidet die Lesbarkeit. (Bei einwöchigen Themen wie "CSP" oder "DTL" würde es aber passen.)

**Comment by cagix** [comment]
Ich trenne mal die beiden Sachen und schiebe den zweiten Punkt in ein neues Issue.

**Comment by cagix** [comment]
> > * Der Fahrplan ist voraussichtlich der am meisten benutzte Teil der Webseite.
> > * In den Shortcut-Links kommt es vor Note/Credits.
> > * Vorgeschlagene Reihenfolge: Team - Kursformat - Fahrplan - Prüfungsform - Materialien
> > * Bei der Vorstellung in der ersten Sprechstunde passt es auch gut in obiger Reihenfolge.
> 
> @cyildiz Merkwürdig, ich hatte dieser Tage auch darüber nachgedacht...
> 
> Ich würde sogar noch einen Schritt weiter gehen: An sich sind alle Informationen bis auf den Fahrplan nur für den ersten Termin wichtig und im laufenden Semester nicht mehr relevant. Oft hat man dafür dann eine extra Unterseite "Syllabus". Das hatten wir schon mal, aber ich finde es eigentlich schöner, wenn alle relevanten Dinge zur Orga auf einer Seite zu finden sind.
> 
> Die Materialien hatte ich extra nach vorne gezogen, damit es nicht so wirkt, als ob sie nicht wirklich relevant sind.
> 
> Ich hatte auch überlegt, ob man die Abschnitte ausklappbar macht. Aber das verbessert die Lesbarkeit nicht wirklich aus meiner Sicht.
> 
> Wenn ich Studi wäre, würde ich mir einfach einmal einen Bookmark auf den Fahrplan anlegen und in Zukunft immer direkt dorthin springen.
> 
> Wenn es Dir besser zum Erzählfluss passt, kann ich die Reihenfolge aber gern umstellen.

@cyildiz Ist in 9d100c75200fbdef96282d7982d839ab37b3f5d3 umgesetzt. Ich aktualisiere gleich noch das Lernmodul.

**Comment by cyildiz** [comment]
@cagix, ich hatte das mittel- oder langfristig für nächstes Jahr notiert, quasi um es zur Diskussion zu öffnen.
Du bist schnell :)
Danke auf jeden Fall für die Umsetzung!

> ich finde es eigentlich schöner, wenn alle relevanten Dinge zur Orga auf einer Seite zu finden sind.

Ich finde es so auch besser.

> Die Materialien hatte ich extra nach vorne gezogen, damit es nicht so wirkt, als ob sie nicht wirklich relevant sind.

Das ist auch ein guter Punkt, wir wollen ja eigentlich zum Lesen anregen.
Man hat oft zwei Listen, eine für primäre und dann eine für sekundäre Literatur. Die primäre ist oft das, was man in der Vorlesung direkt liest/behandelt. Aus dieser Hinsicht können wir den Fahrplan vielleicht als primären Stoff, und die Materialien als zusätzlichen Stoff betrachten und hintereinander listen?
Das jetzt nur als Randnotiz für die mittelfristige Betrachtung...

**Comment by cagix** [comment]
> > Die Materialien hatte ich extra nach vorne gezogen, damit es nicht so wirkt, als ob sie nicht wirklich relevant sind.
> 
> Das ist auch ein guter Punkt, wir wollen ja eigentlich zum Lesen anregen. Man hat oft zwei Listen, eine für primäre und dann eine für sekundäre Literatur. Die primäre ist oft das, was man in der Vorlesung direkt liest/behandelt. Aus dieser Hinsicht können wir den Fahrplan vielleicht als primären Stoff, und die Materialien als zusätzlichen Stoff betrachten und hintereinander listen? Das jetzt nur als Randnotiz für die mittelfristige Betrachtung...

Hmmm. Dazu kommt auch noch, dass in den einzelnen Sitzungen auch nochmal Literaturhinweise gegeben werden - die weichen teilweise von den allgemeinen Empfehlungen ab.

Ehrlich gesagt bin ich nicht so sicher, ob sich irgendwas ändern würde, wenn wir noch zw. Primär- und Sekundär-Literatur unterscheiden würden. Ich vermute, der Anteil der Studis, die tatsächlich in ein Buch oder andere Quellen schauen, ist nahe Null. Zudem haben wir mit unserem Material (Skript, Slides, Video) bereits einen in sich geschlossenen Ansatz - es gibt kaum Gründe, warum jemand parallel sich noch andere Literatur anschauen sollte, es ist ja bereits (scheinbar) alles vorhanden.

---

Für neue Module würde ich konsequent einen wesentlich schlankeren Ansatz fahren: 
- (a) Individuelle Vorbereitung: Studis bereiten sich mit fremden, von mir kuratierten Quellen (Literatur, Blogs, Videos) vor, 
- (b) Sprechstunde/Flipped Sitzung: ich präsentiere eine kurze Zusammenfassung (das aktuelle "TL;DR"), danach rechnen wir gemeinsam bzw. in Kleingruppen vertiefenden Beispiele (die aktuellen "Challenges"), ggf. erfolgt gemeinsam eine Erweiterung des Themas (ich erzähle was oder die Studis schauen sich was an und dann gibt es noch eine gemeinsame Aufgabe dazu), 
- (c) Übung: Studis vertiefen und übertragen das Wissen anhand der Aufgaben, zusätzlich erfolgt auch eine Erweiterung des Themas (eigenständiges Erarbeiten von aufbauendem Material und Anwendung auf ein gestelltes Problem), und 
- (d) Grading: Umstellung auf Standards-based Grading oder Specifications Grading. 
 
D.h. ich bespreche quasi die Basics und die Studis dürfen von dort aus angeleitet selbst die weiteren Sachen entdecken. Vielleicht würde ich noch ein zum Thema passendes Beispiel in einem eigenen Video zur Vorbereitung demonstrieren (vorrechnen oder was auch immer grad passt). 

Damit wird die Literatur aus der aktuellen Nebenrolle wieder in den Fokus geschoben. Außerdem spart das extrem viel Arbeit beim Erstellen der Folien und Skripte wie auch bei der Maintenance.

Ich würde dann nur noch zu jedem Thema ein paar Beispiele und eine Zusammenfassung im Repo haben. Zusätzlich natürlich der Fahrplan und Syllabus plus die Übungszettel.

Die Umstellung beim Grading könnte so aussehen: Zu jedem Thema gibt es ein paar Learning Outcomes auf verschiedenen Leveln nach Bloom. Die Studis bekommen die Gelegenheit, das Erlangen der Outcomes mehrfach unter Beweis zu stellen, etwa in zwei verschiedenen Aufgaben auf unterschiedlichen Übungszetteln. Ich würde dann die Aufgaben nur noch "bestanden" bzw. "revision nötig" (plus inhaltliche Kommentare) graden (immer in Bezug auf die Outcomes oder Standards) - und es gibt dann eine Tabelle, welche und wieviele Outcomes erlangt sein müssen für eine bestimmte Abschlussnote. Die Zwischen- und Abschlussklausuren würden dann auch wieder in diesem Sinne verschiedene Outcomes adressieren und in das Schema reinspielen.
